algolia:
  application_id: 7RXZLDVR5F
  files_to_exclude:
  - index.html
  - index.md
  - search.html
  index_name: cockroachcloud_docs
  search_api_key: 372a10456f4ed7042c531ff3a658771b
  settings:
    attributesForFaceting:
    - searchable(categories)
    - searchable(collection)
    - docs_area
    - searchable(tags)
    - searchable(title)
    - type
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
exclude:
- __tests__
- build
- scripts
- vendor
- jekyll-algolia-dev
- archived
- package.json
- package-lock.json
prod_url: https://www.cockroachlabs.com/docs/
homepage_title: CockroachDB Docs
include:
- _redirects
jekyll-minifier:
  compress_css: 'false'
  compress_javascript: 'true'
  compress_js_templates: 'false'
  compress_json: 'true'
  exclude:
  - '**.html'
  - js/rapidoc-min.js
  preserve_line_breaks: 'false'
  preserve_php: 'true'
  remove_comments: 'true'
  remove_form_attributes: 'false'
  remove_http_protocol: 'false'
  remove_https_protocol: 'false'
  remove_input_attributes: 'false'
  remove_intertag_spaces: 'false'
  remove_javascript_protocol: 'false'
  remove_link_attributes: 'false'
  remove_multi_spaces: 'false'
  remove_quotes: 'false'
  remove_script_attributes: 'false'
  remove_spaces_inside_tags: 'false'
  remove_style_attributes: 'false'
  simple_boolean_attributes: 'false'
  simple_doctype: 'false'
  uglifier_args:
    harmony: 'true'
jekyll_get_json:
- data: cloud_api_releases
  json: https://cockroachlabs.cloud/assets/docs/api/manifest.json
- data: all_releases
  json: https://www.cockroachlabs.com/docs/releases/internal/releases.json
- data: all_versions
  json: https://www.cockroachlabs.com/docs/releases/internal/versions.json
keep_files:
- _internal
main_url: https://www.cockroachlabs.com
markdown: Redcarpet
plugins:
- jekyll-include-cache
- jekyll-last-modified-at
- jekyll-minifier
- jekyll-get-json
release_info:
  v1.0:
    build_time: 2018/02/13 15:13:51 (go1.8.3)
    docker_image: cockroachdb/cockroach
    name: v1.0.7
    start_time: 2017-02-13 13:33:22.046027038 -0400 EDT
    version: v1.0.7
sass:
  quiet_deps: 'true'
  sass_dir: css
  style: compressed
site_title: CockroachDB Docs
version: v1.0